controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

_health_check_bundle_routes:
    resource: '@HealthCheckBundle/Resources/config/routes.yaml'
