name: Image build tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    name: Build docker image
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag
        id: image_tag
        run: echo "::set-output name=value::smartassert/suites:$(date +%s)"

      - name: Build
        run: docker build -t ${{ steps.image_tag.outputs.value }} .

      - name: Verify application has more than zero routes
        run: |
          ROUTES=$(docker run ${{ steps.image_tag.outputs.value }} php bin/console debug:router --format=json)
          
          if [ "[]" == "$ROUTES" ]; then
            exit 1
          fi
